name: dark Matter Labs
favicon: null
layout_spectrum: 0.40095989499241114
typography_spectrum: 0.3032041161786765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6645703373942524
  lightness: 0.20910761412233114
  saturation: 0.37205431796610355
  rhythmicContrast: 0.9350354054477066
purpose: []
